spring:
  profiles:
    include: jpa, kafka, redis

server:
  port: 8081

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
